enum FileType{png,jpg,jpeg,csv,txt,xlx,xls,pdf}

enum HtmlType {
  TERMS_AND_CONDITION,
  ABOUT_US,
  PRIVACY_POLICY,
  REFUND_POLICY,
  CANCELLATION_POLICY,
  RETURN_POLICY
}

enum NoDataType {
  REQUEST,
  NOTIFICATION,
  FAQ,
  CONVERSATION,
  TRANSACTION,
  OTHERS,
  SERVICE
}